In [1]:

import pandas as pd

df = pd.DataFrame({
"id":[1,2,3,4],
"color":["red","blue","green","red"],
"size":["Small","Medium","Large","Medium"],
"price":[10,12,15,11]
})

df

   id  color    size  price
0   1    red   Small     10
1   2   blue  Medium     12
2   3  green   Large     15
3   4    red  Medium     11

In [2]:
d_color = pd.get_dummies(df["color"], prefix="C", dtype=int)

In [3]:
df_encoded = pd.concat([df, d_color], axis=1)

In [4]:
df_encoded = df_encoded.drop("color", axis=1)
print(df_encoded)

   id    size  price  C_blue  C_green  C_red
0   1   Small     10       0        0      1
1   2  Medium     12       1        0      0
2   3   Large     15       0        1      0
3   4  Medium     11       0        0      1

In [5]:
order = {"Small":1,"Medium":2,"Large":3}

In [6]:

df["size"] = df["size"].map(order).astype(int)
df

   id  color  size  price
0   1    red     1     10
1   2   blue     2     12
2   3  green     3     15
3   4    red     2     11